#!/usr/bin/env bash
# starts a flask app 
YNI_MYSQL_USER=yni_dev YNI_MYSQL_PWD=yni_dev_pwd YNI_MYSQL_HOST=127.0.0.1 YNI_MYSQL_DB=yni_db YNI_STORAGE_TYPE=db API_HOST=0.0.0.0 API_PORT=5001 python3 -m "$1"
